### ISSUE TITLE
create_chrominfo.py ?

### ISSUE THREAD

**Issue by ollenordesjo** [pkerpedjiev/nometonome#1]
Hi!

Just wanted to check if the create_chrominfo.py script is missing? I can't seem to find it in the repo?

Thanks!

**Comment by pkerpedjiev** [comment]
Originally this repo depended on `clodius` where `create_chrominfo.py` is defined. But since clodius is no longer necessary I just added it here now.

**Comment by ollenordesjo** [comment]
Thanks a lot!
